services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: kraspy
      POSTGRES_PASSWORD: password  # Обязательный

  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  pgdata: